Args = \
    --enable-native-access=ALL-UNNAMED \
    --no-fallback \
    --enable-preview \
    --initialize-at-build-time=io.opentdf.fory.ForyRegistry \
    --initialize-at-run-time=io.opentdf.ffm.internal.NativeBindings \
    -H:+ReportExceptionStackTraces
