/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/opentdf/platform/cmd/libopentdf */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 8 "main.go"

#include <stdint.h>
#include <stdlib.h>

// Error codes
#define OPENTDF_OK 0
#define OPENTDF_ERR_INVALID_HANDLE 1
#define OPENTDF_ERR_INVALID_INPUT 2
#define OPENTDF_ERR_SERIALIZATION 3
#define OPENTDF_ERR_INTERNAL 4
#define OPENTDF_ERR_NOT_FOUND 5
#define OPENTDF_ERR_UNAUTHORIZED 6
#define OPENTDF_ERR_BUFFER_TOO_SMALL 7

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern uint64_t PlatformNew(char* configPtr);
extern void PlatformFree(uint64_t handle);
extern int PlatformGetVersion(char* versionPtr, int* versionLen);
extern int KASGetPublicKey(uint64_t handle, int algorithm, uint8_t* keyPtr, int* keyLen);
extern int KASRewrap(uint64_t handle, uint8_t* requestPtr, int requestLen, uint8_t* responsePtr, int* responseLen);
extern int AuthGetDecision(uint64_t handle, uint8_t* entityPtr, int entityLen, uint8_t* resourcePtr, int resourceLen, uint8_t* decisionPtr, int* decisionLen);
extern int AuthGetEntitlements(uint64_t handle, uint8_t* entityPtr, int entityLen, uint8_t* entitlementsPtr, int* entitlementsLen);
extern int PolicyListAttributes(uint64_t handle, char* namespacePtr, uint8_t* attributesPtr, int* attributesLen);
extern int PolicyGetAttributeValues(uint64_t handle, uint8_t* fqnsPtr, int fqnsLen, uint8_t* valuesPtr, int* valuesLen);
extern int EntityResolve(uint64_t handle, char* tokenPtr, int tokenLen, uint8_t* entityChainPtr, int* entityChainLen);

#ifdef __cplusplus
}
#endif
